added tech journey
iamshadmirza/TheNextBigWriter pull request #23
Opened 2020-03-25 18:41 UTC by PragatiVerma18

added my tech journey

2020-03-29 09:01 UTC, kamleshchandnani requested changes

2020-03-29 09:01 UTC, kamleshchandnani commented on Tech Journey/How I got into tech.md
> +To begin with my writing journey, I feel that I must introduce myself, and what's better than to write about my journey in tech and give an insight into what brought me here.
```suggestion
To begin with my writing journey, I felt that I shall start with introducing myself, and what's better than to write about my journey in tech and give an insight into what brought me here.
```

2020-03-29 09:01 UTC, kamleshchandnani commented on Tech Journey/How I got into tech.md
> +I have been enthusiastic about how the software stuff works, what goes behind the screen of my computer and I always imagined how they're made. I have been keenly interested in computer science since
```suggestion
I have been enthusiastic about how the software stuff works, what goes behind the screen of my computer and I always imagined how they're made. I have been keen in computer science since school whether they taught us QBasic, LOGO, VisualC++, SQL, HTML, programming in C++ or networking. Anything related to computer science lured me to read and know more about it. What added to my childhood fantasies was the movie - Jobs(2013) which got me really interested in the life of the tech giant and visionary Steve Jobs. Thereafter, I read several books on his life and wished to be as great as him someday. But as he once said- 
```

2020-03-29 09:01 UTC, kamleshchandnani commented on Tech Journey/How I got into tech.md
> +I always wanted to study Computer Science but getting admission in a good college with CS/IT stream is no more an easy deal. You got to almost kill yourself studying Physics, Chemistry and Maths to p
```suggestion
I always wanted to study Computer Science but getting admission in a good college with CS/IT stream is no more an easy deal. You almost kill yourself studying Physics, Chemistry and Maths to pass those entrance exams with good marks. I passed the entrance exams I gave but was just on the borderline with the cut-off marks in hand, which led to me a third-tier college affiliated to AKTU, although, I was happy that it was quite famous for its Computer Science Graduates doing really well with decent placement offers in big firms. Meanwhile, I started writing articles for [fossbytes.com](https://fossbytes.com/author/pragati/).
```

2020-03-29 09:01 UTC, kamleshchandnani commented on Tech Journey/How I got into tech.md
> +As I bumped into college life, I got introduced to the cool and awesome technical student societies/clubs of the college, and then it become my prime goal to get in the best of them and try to improv
```suggestion
As I bumped into college life, I got introduced to the cool and awesome technical student societies/clubs of the college, and then it became my prime goal to get in the best of them and try to improve my technical skills and get the best out of it. Moreover, I kept reading books about Elon Musk, Linus Torvalds and Bill Gates. In the first year itself, I was introduced to the world of competitive coding, I thought maybe I can do this. So, I began practicing on platforms like [CodeChef](https://www.codechef.com/users/pragativerma18) and [HackerRank](https://www.hackerrank.com/itispragativerma) etc. It went smooth for sometime, I was able to do 2-3 questions in a long challenge but there came a time when I realised that this isn't something I was looking for. I began exploring more options, where I thought that web development might be fun, so I switched to development. Competitive Coding is important due to its own reasons but I wanted to create products that might be impactful and can be useful.
```

2020-03-29 09:01 UTC, kamleshchandnani commented on Tech Journey/How I got into tech.md
> +Meanwhile, I was exploring the world of open source software and decided to learn how to use git and GitHub, such that I can try to contribute to open source in whichever way possible. I also kept lo
```suggestion
Meanwhile, I was exploring the world of open source software and decided to learn how to use git and GitHub, such that I can try to contribute to open source in whichever way possible. I also kept looking for internship opportunities and fortunately, I got a web development intern role at a startup named [Uneako](http://uneako.com/). We also started exploring hackathons nearby our college, our first hackathon being hackit@BVP1.0 at BVP, Delhi. It was an enriching experience to be part of such hackathons and meetups, as they open a window and help you evolve to be a better person. They give us a chance to introspect what we have been lacking or what more is to be done to be the winner in your chosen arena of work or ambition. Often, they are the inspiration of new beginnings or the genesis of better future.
```

2020-03-29 09:01 UTC, kamleshchandnani commented on Tech Journey/How I got into tech.md
> +Then, I came across [Google Code-In](https://codein.withgoogle.com/), I thought if I could have known and participated in it when I was in school, it would've been great. However, I saw a chance that
```suggestion
Then, I came across [Google Code-In](https://codein.withgoogle.com/), I thought if I could have known and participated in it when I was in school, it would've been great. However, I saw a chance that I could apply as a mentor, so I did. I was selected as a Google Code-In Mentor for [CircuitVerse.org](https://circuitverse.org/) and it was truly an incredible journey to see so many young individuals participate and contribute to open source. Thereafter, I mentored a few other open source events like- NWoC(IIT Patna), KWoC KOSS(IIT Kharagpur), JMOC(JIIT Noida) and currently I am [GSSoC](https://www.gssoc.tech/)(GirlScript Foundation) Mentor for 'Water Monitoring System'.
```

2020-03-29 09:01 UTC, kamleshchandnani commented on Tech Journey/How I got into tech.md
> +This journey of mine may not be a big inspiration story, however, this is what made me what I am today.
```suggestion
My journey may not sound as a big inspiration story, however, this is what made me what I am today.
```

2020-03-29 09:01 UTC, kamleshchandnani commented on Tech Journey/How I got into tech.md
> +Today, I am an aspiring full stack web developer, learning to make awesome websites that can cater user demands in an efficient and better way. Furthermore, my team is also a [SIH](http://sih.gov.in/
```suggestion
Today, I am an aspiring full stack web developer, learning to make awesome websites that can cater user demands in an efficient and better way. Furthermore, my team is also a [SIH](http://sih.gov.in/) finalist this year. Also, I am eager to share my knowledge and understanding of things, so I decided to write, and hence, I am here with the Next Big Writer. 
```

2020-03-30 18:37 UTC, PragatiVerma18 commented
Everything is resolved. Is that fine now?

2020-03-31 03:37 UTC, merged