bubbling-and-capturing
iamshadmirza/TheNextBigWriter pull request #44
Opened 2020-06-27 15:59 UTC by afrazchelsea

Hey mentors,

I wrote about Event Bubbling and Event Capturing in Javascript. Please have a look.

2020-07-03 06:27 UTC, iamshadmirza commented on js/bubbling-and-capturing.md
> +The interactivity of our HTML web page is handled by Javascript. This interactivity is nothing but a bunch of events that the HTML elements undergo. How well these events are handled decide how user-
Can you explain a bit more about what are events in javascripts?

2020-07-03 06:34 UTC, iamshadmirza commented on js/bubbling-and-capturing.md
> +** Bubbling is the flow of events where, when an event takes place on an element, it first runs the handler on itself, then on its parent and then on all of its ancestors. **
Double star is not needed here. Don't start a paragraph with bold text. Use bold when you want reader to specifically pay attention to a certain thing. The reader already has your attention here.

2020-07-03 06:35 UTC, iamshadmirza commented on js/bubbling-and-capturing.md
> +** In Event Capturing, the event propagation takes place from the outermost element to the innermost element. ** Event capturing is sometimes also referred to as ** event trickling **.
Don't use space after/before the double star. Bold will not work.

2020-07-03 06:36 UTC, iamshadmirza requested changes
Added some comments

2020-07-04 10:44 UTC, afrazchelsea commented
Hey Shad, I made a few changes. Please have a look

2020-07-04 10:57 UTC, merged