added post/how-do-i-use-absolute-position
iamshadmirza/TheNextBigWriter pull request #46
Opened 2020-08-16 10:09 UTC by hussamkhatib

2020-08-17 05:22 UTC, iamshadmirza commented
Hi @hussamkhatib 
Great article. There are few spelling mistakes and punctuation errors  
Can you please review it using Grammarly once?

Go to https://app.grammarly.com and paste your article in a new document. It will tell you about the errors and then you can fix it.

2020-08-17 15:20 UTC, hussamkhatib commented
hey ! i have made the changes  ,thank you for pointing out the mistakes

2020-08-18 05:24 UTC, iamshadmirza commented on css/How-do-i-use-absolute-position/How-do-i-use-absolute-position.md
> +# How do i use absolute position in css
Make "I" uppercase

2020-08-18 05:25 UTC, iamshadmirza commented on css/How-do-i-use-absolute-position/How-do-i-use-absolute-position.md
> + We can directly push the element to any extreme side by specifying to **0**,
extreme side by specifying that direction  to **0*

2020-08-18 05:27 UTC, iamshadmirza commented on css/How-do-i-use-absolute-position/How-do-i-use-absolute-position.md
> +If we uncomment the position property we can see that the div elements are out of flow with the document and only the p element consumes the space here, also all elements are overlapping, we can choo
Instead of using "also", break the sentence in two smaller sentences. It will help the reader to understand what's going on.

2020-08-18 05:29 UTC, iamshadmirza commented on css/How-do-i-use-absolute-position/How-do-i-use-absolute-position.md
> +It's is best  not overuse absolute positioning because it can be pretty difficult to maneuver especially when  you are making your website responsive.
Use "recommended" instead of saying it's best not overuse...

There is extra space after "when"

2020-08-18 05:30 UTC, iamshadmirza commented on css/How-do-i-use-absolute-position/How-do-i-use-absolute-position.md
> +It's is best  not overuse absolute positioning because it can be pretty difficult to maneuver especially when  you are making your website responsive.
Instead of Conclusion, you can give heading as "Takeaways" and recall what you explained in this article. Most readers are looking for that

2020-08-18 05:30 UTC, iamshadmirza requested changes
I've left some comments that will improve the overall article. Please take a look.

2020-08-22 11:02 UTC, hussamkhatib commented
> I've left some comments that will improve the overall article. Please take a look.

sure , i have the changes now

2020-08-23 05:54 UTC, iamshadmirza commented
Looks perfect!
Congratulations. Good job.
I would suggest you publish around 1-3 pm on Monday to gain the most reach.
Once you have published on your blog, you can submit to the published with original link.

2020-08-23 05:54 UTC, merged

2020-08-23 15:38 UTC, hussamkhatib commented
thank you Shad .
I don't have a blog website ,i will directly publish it here in hashnode

2020-08-24 04:41 UTC, iamshadmirza commented
You can post on your hashnode blog then submit to the publication.

2020-08-24 08:38 UTC, hussamkhatib commented
done , i have published it on hashnode